# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 540635d7f4f0b0cd5d0cf7358ebf3991d9189eecf782d18ad6187fbe4b0a6f8d446959fd5ee1e636733d9de5f080429b8918070729657b81e5077bcb1eeb3f35

test:
  secret_key_base: 1ca1cdc6666911b3fea8b2168b3bdb118f3afc882ed23cbd0e5f05182954f4874beae65be9946564fdade9db6cd8c6651a94bb8b96ebc2a26f13546bc22fedfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
